name: Reload Node Server on Push
run-name: ${{ github.actor }} is pushing to main

on:
    push:
        branches:
            - "main"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
            # - name: build docker image
            #   run: docker build --tag victorsandru/bard-chimes
